-- Run from the repository root: lua5.1 tests/checklist.lua
-- Shared game stubs, real checklist constructors and callbacks.
dofile('tests/new-tools.lua')
local ST, checks = SimpleTools, 0
assert(loadfile('SimpleChecklist.lua'))('SimpleTools', ST)
local methods=getmetatable(CreateFrame()).__index
function methods:CreateTexture() return CreateFrame() end
function methods:SetColorTexture() end
function methods:GetStringWidth() return #self.text*5 end
function methods:SetChecked(value) self.checked=value end
local function equal(actual,expected)
    assert(actual==expected,tostring(actual)..' ~= '..tostring(expected))
    checks=checks+1
end
local frame=ST:CreateChecklistUI(ST.contentFrame)
ST.tabFrames[10]=frame
local view=ST.checklistViews[1]
equal(view.empty.shown,true)
equal(ST:AddChecklistItem('  '),false)
equal(ST:AddChecklistItem(string.rep('a',121)),false)
view.input:SetText('  Visit bank  ')
view.input.scripts.OnEnterPressed()
equal(ST.checklistItems[1].text,'Visit bank')
equal(view.input:GetText(),'')
equal(ST.db.checklist.items[1].text,'Visit bank')
ST:AddChecklistItem('Buy water')
ST:AddChecklistItem('Repair')
local first,second,third=unpack(ST.checklistItems)
view.rows[1].check.scripts.OnClick()
equal(first.checked,true)
equal(view.rows[1].strike.shown,true)
equal(ST.db.checklist.items[1].checked,true)
equal(ST.checklistItems[2],second)
ST:ShowChecklistProjected(true)
local overlay=ST.checklistViews[2]
equal(overlay.rows[1].check.checked,true)
equal(overlay.rows[1].strike.shown,true)
overlay.rows[1].check.scripts.OnClick()
equal(first.checked,false)
equal(view.rows[1].check.checked,false)
view.rows[2].scripts.OnClick(view.rows[2])
equal(ST.checklistEditing,second)
ST.checklistEditInput:SetText('Buy food and water')
ST.checklistEditInput.scripts.OnEnterPressed()
equal(second.text,'Buy food and water')
equal(overlay.rows[2].text.text,'Buy food and water')
equal(ST.checklistEditFrame.shown,false)
equal(ST.checklistItems[2],second)
ST:EditChecklistItem(first)
ST.checklistEditInput:SetText('')
ST.checklistEditInput.scripts.OnEnterPressed()
equal(first.text,'Visit bank')
equal(ST.checklistEditFrame.shown,true)
ST.checklistEditInput.scripts.OnEscapePressed()
equal(ST.checklistEditFrame.shown,false)
ST:EditChecklistItem(second)
view.rows[2].remove.scripts.OnClick()
equal(#ST.checklistItems,2)
equal(ST.checklistItems[2],third)
equal(ST.checklistEditFrame.shown,false)
equal(ST:ChangeChecklistItem(second,'Wrong task'),false)
equal(ST:RemoveChecklistItem(second),false)
ST:ToggleChecklistItem(first)
ST:ToggleChecklistItem(third)
overlay.reset.scripts.OnClick()
equal(first.checked,false)
equal(third.checked,false)
equal(first.text,'Visit bank')
equal(#ST.checklistItems,2)
ST:ToggleChecklistItem(first)
ST:SelectTab(10)
ST.checklistProjectedFrame:SetPoint('CENTER',UIParent,'CENTER',14,28)
ST:SaveDB()
assert(ST.db.checklist.items[1]~=first); checks=checks+1
ST.checklistItems={}
ST:LoadState()
equal(ST.db.ui.selectedTab,10)
equal(#ST.checklistItems,2)
equal(ST.checklistItems[1].checked,true)
equal(ST.checklistItems[2].text,'Repair')
equal(ST.checklistProjectedFrame.shown,true)
equal(ST.checklistProjectedFrame.point[4],14)
equal(ST.checklistProjectedFrame.point[5],28)
ST.checklistProjectedFrame.closeButton.scripts.OnClick()
equal(ST.db.checklist.projected,false)
equal(#ST.checklistItems,2)
for i=1,50 do ST:AddChecklistItem('Task '..i) end
equal(#view.rows,52)
equal(view.rows[52].shown,true)
equal(view.child.height,52*24)
local cleaned=ST:CopyChecklistItems({{text=' Good ',checked=true},{text=''},false,{text=3}})
equal(#cleaned,1)
equal(cleaned[1].text,'Good')
equal(cleaned[1].checked,true)
-- Deleting the final task clears both views without leaving active stale rows.
while #ST.checklistItems>0 do ST:RemoveChecklistItem(ST.checklistItems[1]) end
equal(view.empty.shown,true)
equal(overlay.empty.shown,true)
equal(view.rows[1].shown,false)
equal(view.reset.enabled,false)
print(string.format('PASS: %d checklist assertions',checks))
